# Data exploration with Pandas

###  Tree of Life
<table><tr><td><img src="http://t3.gstatic.com/licensed-image?q=tbn:ANd9GcSq4PRaxgfpjNOSe81JgN8l71DWtDHpkSfH3xo8EOk7khAlqQozXnJm8ubupyHj" width=300></td><td>
<img src="https://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2008/04/17/DarwinSketch.article.jpg?width=445&quality=85&auto=format&fit=max&s=c7f89552d12b8495b2b4eb4d7a5bc391" width=300></td><td><img src="https://i.pinimg.com/originals/78/3f/98/783f983d622b06b9a990ad67efabbbe8.png" width=300></td></tr></table>

### Objective of this notebook
We will continue our data exploration with a dataset that focuses on biological concept of Taxonomic classifications. In this notebook, we will tackle real world questions with pandas. We will explore a Kingdom of Life dataset. Each row in this data set represents a particular organism. Each organism is classified in a particular Kingdom and Class.

In [ ]:
### Import libraries
import pandas as pd

In [ ]:
### Notice this dataset is separated by tab instead of comma
euk_filepath = "https://raw.githubusercontent.com/csbfx/advpy122-data/master/euk.tsv"
euk_df = pd.read_csv(euk_filepath, sep=('\t'))

In [3]:
### A reminder of what columns are in this dataset and the size of the dataframe

euk_df.info()
print("Rows and columns:", euk_df.shape)

<class 'pandas.DataFrame'>
RangeIndex: 8302 entries, 0 to 8301
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Species             8302 non-null   str
 1   Kingdom             8302 non-null   str
 2   Class               8302 non-null   str
 3   Size (Mb)           8302 non-null   float64
 4   GC%                 8302 non-null   str
 5   Number of genes     8302 non-null   str
 6   Number of proteins  8302 non-null   str
 7   Publication year    8302 non-null   int64
 8   Assembly status     8302 non-null   str
dtypes: float64(1), int64(1), str(7)
memory usage: 583.9 KB
Rows and columns: (8302, 9)

#### Sorting columns
Recall that you can sort columns using the function `sort_values()`. Using the parameter `ascending=<True or False>`, the values can be sorted in ascending or descending order. If you sort more than one columns, the first column will be sorted first, then the rows with identical values in column 1 will be sorted based on the value in the second column.

In [4]:
### You can sort by one or more columns
## Sort the 'Species' column ascending, and 'Publication year' descending.
## What can be said about the order or Publication year relative to Species?

sorted_euk = euk_df.sort_values(['Species', 'Publication year'], ascending=[True, False])
display(sorted_euk.head(10))
print('Species are alphabetical; publication years descend within each species, not globally.')

,Species,Kingdom,Class,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status
2968,Abeoforma whisleri,Protists,Other Protists,101.5540,31.4,-,-,2017,Scaffold
3764,Abrus precatorius,Plants,Land Plants,347.2300,31.8,28735,40048,2018,Scaffold
2467,Absidia glauca,Fungi,Other Fungi,48.7464,44.5,15117,14891,2016,Scaffold
2695,Absidia repens,Fungi,Other Fungi,47.4229,38.2,15151,14915,2017,Contig
1905,Acanthamoeba astronyxis,Protists,Other Protists,83.4325,42.9,-,-,2015,Scaffold
5103,Acanthamoeba castellanii,Protists,Other Protists,115.0500,58.9,-,-,2015,Scaffold
4927,Acanthamoeba castellanii,Protists,Other Protists,46.7146,58.3,-,-,2011,Scaffold
163,Acanthamoeba castellanii str. Neff,Protists,Other Protists,42.0198,57.8,15655,14974,2012,Scaffold
2657,Acanthamoeba comandoni,Protists,Other Protists,86.2147,43.7,-,-,2017,Contig
1906,Acanthamoeba culbertsoni,Protists,Other Protists,55.5438,50.4,-,-,2015,Scaffold

Species are alphabetical; publication years descend within each species, not globally.

### Q1. How many fungal species have genomes size bigger than 100Mb? What are their names?

**We need to filter a few things to address this question.**
1. Select all the Fungi under the "Kingdom" column.
2. Select all the Fungi with genome size greater than 100.
3. Select Species from the filtered data from step 2 above.

**Let's do it step by step. And then we will combine all of them in one line of code.**

In [5]:
### Filter dataframe and narrow down to only Kingdom that includes Fungi

fungi_large = euk_df.loc[euk_df['Kingdom'] == 'Fungi']
fungi_large.head()

,Species,Kingdom,Class,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status
8,Saccharomyces cerevisiae S288C,Fungi,Ascomycetes,12.15710,38.1556,6445,6002,1999,Complete Genome
10,Pneumocystis carinii B80,Fungi,Ascomycetes,7.66146,27.8,3695,3646,2015,Contig
11,Schizosaccharomyces pombe,Fungi,Ascomycetes,12.59130,36.0381,6974,5132,2002,Chromosome
12,Aspergillus nidulans FGSC A4,Fungi,Ascomycetes,30.27600,50.2721,9586,9556,2003,Scaffold
13,Aspergillus fumigatus Af293,Fungi,Ascomycetes,29.38500,49.8105,19832,19260,2005,Chromosome

To **combine two conditional statements** in the filtering, we need to surround each conditional statements with its own pair of **parentheses**.

In [6]:
### Narrow down to Fungi that has genome size > 100

fungi_large = euk_df.loc[(euk_df['Kingdom'] == 'Fungi') & (euk_df['Size (Mb)'] > 100)]
fungi_large

,Species,Kingdom,Class,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status
323,Blumeria graminis f. sp. hordei DH14,Fungi,Ascomycetes,124.489,43.5,-,-,2018,Scaffold
347,Puccinia triticina 1-1 BBBD Race 1,Fungi,Basidiomycetes,135.344,36.8,15539,15685,2009,Scaffold
354,Tuber melanosporum,Fungi,Ascomycetes,124.946,44.9,7496,7496,2010,Scaffold
372,Puccinia striiformis f. sp. tritici,Fungi,Basidiomycetes,156.834,44.4,-,-,2018,Contig
427,Melampsora larici-populina 98AG31,Fungi,Basidiomycetes,101.129,41.3,16380,16372,2011,Scaffold
...,...,...,...,...,...,...,...,...,...
6406,Rhizophagus irregularis,Fungi,Other Fungi,131.335,25.8,24574,24485,2016,Scaffold
6502,Rhizophagus irregularis,Fungi,Other Fungi,211.467,-,-,-,2018,Scaffold
6511,Rhizophagus irregularis,Fungi,Other Fungi,156.891,-,-,-,2018,Scaffold
6520,Puccinia striiformis,Fungi,Basidiomycetes,144.837,44.2,-,-,2019,Scaffold
6579,Puccinia striiformis f. sp. tritici CY32,Fungi,Basidiomycetes,130.485,45.2,-,-,2013,Scaffold

In [7]:
### To select Species that are Fungi with genome size > 100 Mb

large_fungal_species = fungi_large['Species'].drop_duplicates()
print('Number of unique fungal species:', large_fungal_species.nunique())
large_fungal_species

Number of unique fungal species: 57

323                Blumeria graminis f. sp. hordei DH14
347                  Puccinia triticina 1-1 BBBD Race 1
354                                  Tuber melanosporum
372                 Puccinia striiformis f. sp. tritici
427                   Melampsora larici-populina 98AG31
839                             Ophiocordyceps sinensis
1080                                    Gigaspora rosea
1308                   Leucoagaricus gongylophorus Ac12
1369                           Hemileia vastatrix HvCat
1436                          Cenococcum geophilum 1.58
1470                               Tricholoma matsutake
1504                       Choiromyces venosus 120613-1
1538                        Sphaerobolus stellatus SS14
1555    Rhizophagus irregularis DAOM 181602=DAOM 197198
1563                                    Oehlia diaphana
1586                                Glomus cerebriforme
1675                              Austropuccinia psidii
1851                              Uromyces viciae-fabae
2266                         Leucoagaricus sp. SymC.cos
2622                                Smittium mucronatum
2703                         Neocallimastix californiae
2733                             Pecoramyces ruminatium
3004        Puccinia coronata var. avenae f. sp. avenae
3094                             Uromyces transversalis
3254                                     Tuber magnatum
3270                                 Rhizophagus clarus
3311                        Cantharellus appalachiensis
3315                             Cantharellus lutescens
3348                           Tricholoma bakamatsutake
3355                             Tricholoma flavovirens
3368                                Albatrellus ellisii
3370                               Chroogomphus rutilus
3371                                   Gomphus sp. MG54
3378                                Tricholoma sp. MG77
3398                                   Tuber calosporum
3401                                    Gomphus bonarii
3475                         Rhizophagus sp. MUCL 43196
3774                           Jimgerdemannia lactiflua
3796                        Jimgerdemannia flammicorona
3805                                Neonothopanus nambi
3911                          Monosporascus sp. CRB-8-3
3987                            Colletotrichum trifolii
4008                               Diversispora epigaea
4291                           Verticillium longisporum
4471                   Basidiobolus meristosporus B9252
4509                     Diaporthe longicolla MSPL 10-6
4913                   Puccinia graminis f. sp. tritici
5162                        Puccinia triticina Race 106
5402                                  Pleurotus eryngii
5765             Blumeria graminis f. sp. tritici 96224
5832               Rhizophagus irregularis DAOM 197198w
6234                    Blumeria graminis f. sp. hordei
6257                            Rhizophagus irregularis
6298                 Blumeria graminis f. sp. hordei K1
6382         Puccinia striiformis f. sp. tritici PST-78
6520                               Puccinia striiformis
6579           Puccinia striiformis f. sp. tritici CY32
Name: Species, dtype: str

### Series convert to list
You can convert the Series from the above #Q1 to a python List using `to_list()` method

In [8]:
# speciesSeries = euk_df[ (euk_df.Kingdom == 'Fungi') &
#                   (euk_df['Size (Mb)'] > 100)
#                  ]["Species"]


### Combine the two steps into one


### Slice for the top 10 on the list

speciesSeries = euk_df.loc[
    (euk_df['Kingdom'] == 'Fungi') & (euk_df['Size (Mb)'] > 100), 'Species'
]
species_list = speciesSeries.to_list()
combined_species_list = euk_df.loc[
    (euk_df['Kingdom'] == 'Fungi') & (euk_df['Size (Mb)'] > 100), 'Species'
].to_list()
combined_species_list[:10]

['Blumeria graminis f. sp. hordei DH14',
 'Puccinia triticina 1-1 BBBD Race 1',
 'Tuber melanosporum',
 'Puccinia striiformis f. sp. tritici',
 'Melampsora larici-populina 98AG31',
 'Ophiocordyceps sinensis',
 'Gigaspora rosea',
 'Leucoagaricus gongylophorus Ac12',
 'Hemileia vastatrix HvCat',
 'Cenococcum geophilum 1.58']

### Q2. How many organisms are there for each Kingdom (plants, animals, fungi, protists, and other), and how many unique species names?

*Hint*: Any time we see a question involving the words ”how many
... for each ...” the answer is `value_counts()`.

In [ ]:
euk_df.Kingdom.value_counts()

Kingdom
Fungi       4494
Animals     2181
Plants       870
Protists     727
Other         30
Name: count, dtype: int64

#### Count unique values
To address "how many unique species names?", count the unique species names for plants by filtering the dataframe. [`nunique()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.nunique.html) returns the number of distinct, non-NA observations for each column (default) or row in a DataFrame

In [10]:
### Count the number of unique plants
euk_df[(euk_df["Kingdom"] == "Plants")]["Species"].nunique()

464

In [11]:
### Write a loop to expand this to the other Kingdoms

Kingdoms = ["Protists", "Plants", "Animals"]

for kingdom in Kingdoms:
    count = euk_df.loc[euk_df['Kingdom'] == kingdom, 'Species'].nunique()
    print(f'{kingdom}: {count} unique species')

Protists: 449 unique species
Plants: 464 unique species
Animals: 1442 unique species

#### To make the above more scalable
Hardcoding the values in kingdom is not scalable, we can implement a more elegant way to get a list of unique kingdom names directly from the dataframe [`unique()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.unique.html) returns unique values in the order of apperance. It does NOT sort.

In [ ]:
### Return an array of unique values in Kingdom
euk_df.Kingdom.unique()

Protists 449
Plants 464
Fungi 2554
Animals 1442
Other 27

### Q3. Get the number of unique values for the other Kingdoms (ie, number of unique protists, plants, fungi, animals, and other).

*Hint: * Use the array above to make it more scalable. Try using a for loop

In [13]:
### Use an array to make it more scalable

for kingdom in euk_df['Kingdom'].dropna().unique():
    count = euk_df.loc[euk_df['Kingdom'] == kingdom, 'Species'].nunique()
    print(f'{kingdom}: {count} unique species')

Protists: 449 unique species
Plants: 464 unique species
Fungi: 2554 unique species
Animals: 1442 unique species
Other: 27 unique species

### Q4. Make a new dataframe containing just the rows for the *Aquila* genus.

**Let go over some biology terminologies**
- The names under the **Species** column are scientific names that made up of a *genus* name and a *species* name separated by a space. Example: *Homo sapiens*. Note: there are some species that don't follow that format and we will ignore them for now.

To solve this problem, we will need to **separate the genus and species names** for each value in the **Species** column.

*Question:* What if there are different number of string in a column, for example "Emiliania huxleyi CCMP1516" versus "Arabidopsis thaliana"?

In [ ]:
### Review how to split a string.
## What if we wanted to split string by ","?
## eg., b = "Homo, sapiens", b_split=b.split(",")
a = "Homo sapiens"
a_split = a.split( )
print(a_split)
print(a_split[0])


### Split the strings stored in the column Species
# euk_df.Species.str.split()
species_list = euk_df.Species.str.split(" ")
species_list

['Homo', 'sapiens']
Homo

0       [Emiliania, huxleyi, CCMP1516]
1              [Arabidopsis, thaliana]
2                       [Glycine, max]
3               [Medicago, truncatula]
4              [Solanum, lycopersicum]
                     ...
8297       [Saccharomyces, cerevisiae]
8298       [Saccharomyces, cerevisiae]
8299       [Saccharomyces, cerevisiae]
8300       [Saccharomyces, cerevisiae]
8301       [Saccharomyces, cerevisiae]
Name: Species, Length: 8302, dtype: object

In [ ]:
### Take the first element of each of the resulting lists (again remembering to refer to the str attribute):
## This gives us our series of genus names.
euk_df.Species.str.split().str[0]

0           Emiliania
1         Arabidopsis
2             Glycine
3            Medicago
4             Solanum
            ...
8297    Saccharomyces
8298    Saccharomyces
8299    Saccharomyces
8300    Saccharomyces
8301    Saccharomyces
Name: Species, Length: 8302, dtype: object

In [ ]:
### Add the condition to get a series of boolean values:
## This can be useful later for filtering based on conditions

euk_df.Species.str.split(' ').str[0] == "Aquila"

0       False
1       False
2       False
3       False
4       False
        ...
8297    False
8298    False
8299    False
8300    False
8301    False
Name: Species, Length: 8302, dtype: bool

In [ ]:
### Plug the above into the original dataframe to select the rows that are True

aquila_data = euk_df[ (euk_df.Species.str.split(' ').str[0] == "Aquila") ]
aquila_data.head(1)

,Species,Kingdom,Class,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status
1755,Aquila chrysaetos canadensis,Animals,Birds,1192.74,41.9001,17520,31284,2014,Scaffold

In [ ]:
## Extract the genus name and combine it with other columns in the dataframe to create a new dataframe
euk_df['Genus']=euk_df.Species.str.split(" ").str[0]

neweuk = euk_df[["Species","Genus","Class","Kingdom"]]
neweuk.head(3)

                      Species        Genus           Class   Kingdom
0  Emiliania huxleyi CCMP1516    Emiliania  Other Protists  Protists
1        Arabidopsis thaliana  Arabidopsis     Land Plants    Plants
2                 Glycine max      Glycine     Land Plants    Plants

### Q5. Which organism have at least 10% more proteins than genes?

There are a few different ways to interpret ”10% more”, but for the purposes of this question we will say that we want to divide the number of proteins by the number of genes, and if the result is greater than or equal to 1.1 then we want to include the organism.

If you look at the `euk` dataframe, you will see that the columns **Number of proteins** and **Number of genes** are mixed with numeric values and dashes. To ensure that all the values in these two columns are numeric, we will use pandas method [`to_numeric`](https://pandas.pydata.org/pandas-docs/version/0.19.2/generated/pandas.to_numeric.html) to convert the values in columns "Number of proteins" and "Number of genes" to numeric datatype. In addition, we will set the `errors` argument to `'coerce'` to convert any non-numeric value to NaN (not a number).

In [ ]:
### Calculate proteins per gene by applying the division for each row. What to do about NaN?
euk_df["Proteins per gene"] = euk_df["Number of proteins"]/euk_df["Number of genes"]
euk_df["Proteins per gene"]
## This returns TypeError: Unable to divide str

TypeError: unsupported operand type(s) for /: 'str' and 'str'

In [ ]:
### What happens if there are non-numeric value in a column?
euk_df["Number of proteins"] =  pd.to_numeric(euk_df["Number of proteins"])
euk_df["Number of proteins"].mean()
## This returns ValueError: Unable to parse string "-"

ValueError: Unable to parse string "-" at position 5

In [21]:
### Covert the values in columns to numeric
## Hint: deal with the NaN
euk_df["Number of genes"] =  pd.to_numeric(euk_df["Number of genes"],  errors='coerce')

## Apply the division for each row to get "Proteins per gene"

euk_df['Number of proteins'] = pd.to_numeric(euk_df['Number of proteins'], errors='coerce')
euk_df['GC%'] = pd.to_numeric(euk_df['GC%'], errors='coerce')
euk_df['Proteins per gene'] = (
    euk_df['Number of proteins'] / euk_df['Number of genes'].where(euk_df['Number of genes'] > 0)
)
# Missing or invalid counts remain NaN and will not pass the >= 1.1 filter.
euk_df['Proteins per gene']

0       1.000130
1       1.259821
2       1.190018
3       1.115310
4       1.207051
          ...
8297         NaN
8298    1.922581
8299         NaN
8300         NaN
8301         NaN
Name: Proteins per gene, Length: 8302, dtype: float64

In [ ]:
### To filter the rows where the ratio of proteins and genes is greater than or equal to 1.1,
## we will get a series of boolean values by setting the condition.

euk_df[(euk_df["Proteins per gene"] >= 1.1)]

,Species,Kingdom,Class,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status,Genus,Proteins per gene
1,Arabidopsis thaliana,Plants,Land Plants,119.669000,36.0529,38311.0,48265.0,2001,Chromosome,Arabidopsis,1.259821
2,Glycine max,Plants,Land Plants,979.046000,35.1153,59847.0,71219.0,2010,Chromosome,Glycine,1.190018
3,Medicago truncatula,Plants,Land Plants,412.924000,34.0470,37603.0,41939.0,2011,Chromosome,Medicago,1.115310
4,Solanum lycopersicum,Plants,Land Plants,828.349000,35.6991,31200.0,37660.0,2010,Chromosome,Solanum,1.207051
6,Oryza sativa Japonica Group,Plants,Land Plants,374.423000,43.5769,35219.0,42580.0,2015,Chromosome,Oryza,1.209007
...,...,...,...,...,...,...,...,...,...,...,...
6487,Fusarium oxysporum f. sp. melonis 26406,Fungi,Ascomycetes,54.034300,47.5000,20030.0,26719.0,2012,Scaffold,Fusarium,1.333949
6523,Fusarium oxysporum Fo47,Fungi,Ascomycetes,49.664600,47.7000,18553.0,24818.0,2012,Scaffold,Fusarium,1.337681
6626,Arabidopsis thaliana,Plants,Land Plants,93.654500,36.0433,16842.0,20111.0,2000,Chromosome,Arabidopsis,1.194098
6781,Mus musculus,Animals,Mammals,3251.250000,41.8306,31682.0,45437.0,2005,Chromosome,Mus,1.434158
8298,Saccharomyces cerevisiae,Fungi,Ascomycetes,0.586761,38.5921,155.0,298.0,1992,Chromosome,Saccharomyces,1.922581

### Indexing in pandas
The indexing operator and attribute selection are nice because they work just like they do in the rest of the Python ecosystem. As a novice, this makes them easy to pick up and use. However, pandas has its own accessor operators, `iloc` and `loc`. For more advanced operations, these are the ones you're supposed to be using.

#### Index-based selection
Pandas indexing works in one of two paradigms. The first is index-based selection: selecting data based on its numerical position in the data.`iloc` follows this paradigm.

To select the first row of data in a DataFrame, we may use the following:

In [ ]:
### New df of only Fungi Kingdom
fungi = euk_df[(euk_df.Kingdom == 'Fungi')]

## Selecting first row of fungi DataFrame
fungi.iloc[0]

Species               Saccharomyces cerevisiae S288C
Kingdom                                        Fungi
Class                                    Ascomycetes
Size (Mb)                                    12.1571
GC%                                          38.1556
Number of genes                               6445.0
Number of proteins                            6002.0
Publication year                                1999
Assembly status                      Complete Genome
Genus                                  Saccharomyces
Proteins per gene                           0.931265
Name: 8, dtype: object

## Review: Extracting rows and columns

-  Extract specific rows and all columns

    ```df.iloc[rows]```

-  Extract specific rows and columns

    ```df.iloc[rows, columns]```

-  Extract specific rows and columns with specific indices

    ```df.iloc[start:stop:skip, start:stop:skip]```

#### Note that stop is exclusive

 ```[1:3]``` will extract the second and third rows for all columns.

```[1::2, :]```  will extract from the 2nd row all the way to the end every other row, and all the columns

```[:, :3]```  all rows, from the beginning to the 3rd column (indices 0, 1, 2)

### Q6. Lets practice extracting particular rows and columns in the DataFrame

In [24]:
### Getting the second and third rows for all columns

fungi.iloc[1:3, :]

,Species,Kingdom,Class,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status,Genus,Proteins per gene
10,Pneumocystis carinii B80,Fungi,Ascomycetes,7.66146,27.8000,3695.0,3646.0,2015,Contig,Pneumocystis,0.986739
11,Schizosaccharomyces pombe,Fungi,Ascomycetes,12.59130,36.0381,6974.0,5132.0,2002,Chromosome,Schizosaccharomyces,0.735876

In [25]:
### Getting every other rows from the first row to the 10th row, and extracting 4th and 5th columns

fungi.iloc[:10:2, 3:5]

    Size (Mb)      GC%
8    12.15710  38.1556
11   12.59130  36.0381
13   29.38500  49.8105
15   14.28270  33.4827
33    2.49752  47.3005

Both loc and iloc are row-first, column-second. This is the opposite of what we do in native Python, which is column-first, row-second.

This means that it's marginally easier to retrieve rows, and marginally harder to get retrieve columns. To get a column with iloc, we can do the following:

In [26]:
## Select all rows, first column

fungi.iloc[:, 0]

8       Saccharomyces cerevisiae S288C
10            Pneumocystis carinii B80
11           Schizosaccharomyces pombe
12        Aspergillus nidulans FGSC A4
13         Aspergillus fumigatus Af293
                     ...
8297          Saccharomyces cerevisiae
8298          Saccharomyces cerevisiae
8299          Saccharomyces cerevisiae
8300          Saccharomyces cerevisiae
8301          Saccharomyces cerevisiae
Name: Species, Length: 4494, dtype: str

On its own, the `:` operator, which also comes from native Python, means "everything". When combined with other selectors, however, it can be used to indicate a range of values. For example, to omit the first 3 columns and extract just the first three rows, we would do:

In [27]:
### Omit the first 3 columns and extract just the first three rows

fungi.iloc[:3, 3:]

,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status,Genus,Proteins per gene
8,12.15710,38.1556,6445.0,6002.0,1999,Complete Genome,Saccharomyces,0.931265
10,7.66146,27.8000,3695.0,3646.0,2015,Contig,Pneumocystis,0.986739
11,12.59130,36.0381,6974.0,5132.0,2002,Chromosome,Schizosaccharomyces,0.735876

#### Label-based selection
The second paradigm for attribute selection is the one followed by the loc operator: label-based selection. In this paradigm, it's the data index value, not its position, which matters.

In [28]:
### Getting all rows, and specific columns ('Species', 'Number of genes', 'Number of proteins') based on their headers

fungi.loc[:, ['Species', 'Number of genes', 'Number of proteins']]

                             Species  Number of genes  Number of proteins
8     Saccharomyces cerevisiae S288C           6445.0              6002.0
10          Pneumocystis carinii B80           3695.0              3646.0
11         Schizosaccharomyces pombe           6974.0              5132.0
12      Aspergillus nidulans FGSC A4           9586.0              9556.0
13       Aspergillus fumigatus Af293          19832.0             19260.0
...                              ...              ...                 ...
8297        Saccharomyces cerevisiae              NaN                 NaN
8298        Saccharomyces cerevisiae            155.0               298.0
8299        Saccharomyces cerevisiae              NaN                 NaN
8300        Saccharomyces cerevisiae              NaN                 NaN
8301        Saccharomyces cerevisiae              NaN                 NaN

[4494 rows x 3 columns]

### Set row index using a specific column
Use `inplace=True` to modify the original DataFrame directly

In [ ]:
### Set index as Species
fungi.set_index('Species', inplace=True)

,index,Kingdom,Class,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status,Genus,Proteins per gene
Species,,,,,,,,,,,
Saccharomyces cerevisiae S288C,0,Fungi,Ascomycetes,12.15710,38.1556,6445.0,6002.0,1999,Complete Genome,Saccharomyces,0.931265
Pneumocystis carinii B80,1,Fungi,Ascomycetes,7.66146,27.8000,3695.0,3646.0,2015,Contig,Pneumocystis,0.986739
Schizosaccharomyces pombe,2,Fungi,Ascomycetes,12.59130,36.0381,6974.0,5132.0,2002,Chromosome,Schizosaccharomyces,0.735876
Aspergillus nidulans FGSC A4,3,Fungi,Ascomycetes,30.27600,50.2721,9586.0,9556.0,2003,Scaffold,Aspergillus,0.996870
Aspergillus fumigatus Af293,4,Fungi,Ascomycetes,29.38500,49.8105,19832.0,19260.0,2005,Chromosome,Aspergillus,0.971158

### Reset dataframe's index

In [ ]:
### Can you retrieve the condition of GC% > 50.00?
GC_fungi = fungi[fungi['GC%'] > 50.00]
GC_fungi

,Kingdom,Class,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status,Genus,Proteins per gene
Species,,,,,,,,,,
Aspergillus nidulans FGSC A4,Fungi,Ascomycetes,30.2760,50.2721,9586.0,9556.0,2003,Scaffold,Aspergillus,0.996870
Phanerochaete chrysosporium,Fungi,Basidiomycetes,39.2051,56.5000,NaN,NaN,2016,Contig,Phanerochaete,NaN
Aspergillus terreus NIH2624,Fungi,Ascomycetes,29.3640,52.8000,10551.0,10401.0,2005,Scaffold,Aspergillus,0.985783
Pyricularia oryzae 70-15,Fungi,Ascomycetes,40.9791,51.5882,13184.0,12989.0,2003,Chromosome,Pyricularia,0.985209
Ustilago maydis 521,Fungi,Basidiomycetes,19.6644,54.0121,6909.0,6782.0,2003,Chromosome,Ustilago,0.981618
...,...,...,...,...,...,...,...,...,...,...
Pyricularia oryzae,Fungi,Ascomycetes,39.3119,51.1000,NaN,NaN,2018,Scaffold,Pyricularia,NaN
Pyricularia oryzae,Fungi,Ascomycetes,37.2516,51.6000,NaN,NaN,2018,Scaffold,Pyricularia,NaN
Pyricularia oryzae,Fungi,Ascomycetes,39.3137,51.2000,NaN,NaN,2018,Scaffold,Pyricularia,NaN
Pyricularia oryzae,Fungi,Ascomycetes,37.8513,51.8000,NaN,NaN,2018,Scaffold,Pyricularia,NaN
Pyricularia oryzae,Fungi,Ascomycetes,39.5550,50.8000,NaN,NaN,2019,Scaffold,Pyricularia,NaN

In [ ]:
### Need to reset the index because GC_fungi is multitier index
GC_fungi.reset_index(inplace=True)

,Species,Kingdom,Class,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status,Genus,Proteins per gene
0,Aspergillus nidulans FGSC A4,Fungi,Ascomycetes,30.2760,50.2721,9586.0,9556.0,2003,Scaffold,Aspergillus,0.996870
1,Phanerochaete chrysosporium,Fungi,Basidiomycetes,39.2051,56.5000,NaN,NaN,2016,Contig,Phanerochaete,NaN
2,Aspergillus terreus NIH2624,Fungi,Ascomycetes,29.3640,52.8000,10551.0,10401.0,2005,Scaffold,Aspergillus,0.985783
3,Pyricularia oryzae 70-15,Fungi,Ascomycetes,40.9791,51.5882,13184.0,12989.0,2003,Chromosome,Pyricularia,0.985209
4,Ustilago maydis 521,Fungi,Basidiomycetes,19.6644,54.0121,6909.0,6782.0,2003,Chromosome,Ustilago,0.981618

In [ ]:
### Getting specific rows based on the row index and all columns
fungi.loc[['Saccharomyces cerevisiae'], :]

,Kingdom,Class,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status,Genus,Proteins per gene
Species,,,,,,,,,,
Saccharomyces cerevisiae,Fungi,Ascomycetes,12.086300,38.1473,NaN,NaN,2015,Complete Genome,Saccharomyces,NaN
Saccharomyces cerevisiae,Fungi,Ascomycetes,12.165500,38.3121,NaN,NaN,2018,Complete Genome,Saccharomyces,NaN
Saccharomyces cerevisiae,Fungi,Ascomycetes,12.134300,38.1573,NaN,NaN,2019,Complete Genome,Saccharomyces,NaN
Saccharomyces cerevisiae,Fungi,Ascomycetes,12.150900,38.5859,NaN,NaN,2015,Chromosome,Saccharomyces,NaN
Saccharomyces cerevisiae,Fungi,Ascomycetes,12.071900,38.3205,NaN,NaN,2016,Chromosome,Saccharomyces,NaN
...,...,...,...,...,...,...,...,...,...,...
Saccharomyces cerevisiae,Fungi,Ascomycetes,3.993920,38.2000,NaN,NaN,2017,Scaffold,Saccharomyces,NaN
Saccharomyces cerevisiae,Fungi,Ascomycetes,0.586761,38.5921,155.0,298.0,1992,Chromosome,Saccharomyces,1.922581
Saccharomyces cerevisiae,Fungi,Ascomycetes,12.020400,38.2971,NaN,NaN,2018,Chromosome,Saccharomyces,NaN
Saccharomyces cerevisiae,Fungi,Ascomycetes,11.960900,38.2413,NaN,NaN,2018,Chromosome,Saccharomyces,NaN
Saccharomyces cerevisiae,Fungi,Ascomycetes,11.820700,38.2536,NaN,NaN,2018,Chromosome,Saccharomyces,NaN

In [ ]:
fungi.reset_index(inplace=True)
fungi.head()

,Species,Kingdom,Class,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status,Genus,Proteins per gene
0,Saccharomyces cerevisiae S288C,Fungi,Ascomycetes,12.15710,38.1556,6445.0,6002.0,1999,Complete Genome,Saccharomyces,0.931265
1,Pneumocystis carinii B80,Fungi,Ascomycetes,7.66146,27.8000,3695.0,3646.0,2015,Contig,Pneumocystis,0.986739
2,Schizosaccharomyces pombe,Fungi,Ascomycetes,12.59130,36.0381,6974.0,5132.0,2002,Chromosome,Schizosaccharomyces,0.735876
3,Aspergillus nidulans FGSC A4,Fungi,Ascomycetes,30.27600,50.2721,9586.0,9556.0,2003,Scaffold,Aspergillus,0.996870
4,Aspergillus fumigatus Af293,Fungi,Ascomycetes,29.38500,49.8105,19832.0,19260.0,2005,Chromosome,Aspergillus,0.971158

**Data visualizing with Pie plot**  
Dataframe has a built-in pie chart plotting(https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.pie.html). While it is not as customizable as later libraries that we will use such as matplotlib, it allows us to quickly plot a pie chart from the dataframe. Additionally you can specify the size plot you want to return using the parameter figsize).

In [ ]:
## Pass in the column that you want to plot as your "y" variable.
fungi.plot.pie(y='Publication year', figsize=(5, 5))