# Data exploration with Pandas

###  Tree of Life
<table><tr><td><img src="http://t3.gstatic.com/licensed-image?q=tbn:ANd9GcSq4PRaxgfpjNOSe81JgN8l71DWtDHpkSfH3xo8EOk7khAlqQozXnJm8ubupyHj" width=300></td><td>
<img src="https://i.guim.co.uk/img/static/sys-images/Guardian/Pix/pictures/2008/04/17/DarwinSketch.article.jpg?width=445&quality=85&auto=format&fit=max&s=c7f89552d12b8495b2b4eb4d7a5bc391" width=300></td><td><img src="https://i.pinimg.com/originals/78/3f/98/783f983d622b06b9a990ad67efabbbe8.png" width=300></td></tr></table>

### Objective of this notebook
We will continue our data exploration with the dataset we used in Colab_Lec04. In this notebook, we will tackle real world questions with pandas. We will explore an kingdom of life data file. Each row in this data set represents a particular organism. An organism is classified in a particular Kingdom and Class.

Notebook adapted from Wendy Lee

In [1]:
# Import libraries
import pandas as pd

In [2]:
### Notice this dataset is separated by tab instead of comma
euk_filepath = "https://raw.githubusercontent.com/csbfx/advpy122-data/master/euk.tsv"
euk_df = pd.read_csv(euk_filepath, sep=('\t'))

In [3]:
### A reminder of what columns are in this dataset and the size of the dataframe
euk_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8302 entries, 0 to 8301
Data columns (total 9 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Species             8302 non-null   str
 1   Kingdom             8302 non-null   str
 2   Class               8302 non-null   str
 3   Size (Mb)           8302 non-null   float64
 4   GC%                 8302 non-null   str
 5   Number of genes     8302 non-null   str
 6   Number of proteins  8302 non-null   str
 7   Publication year    8302 non-null   int64
 8   Assembly status     8302 non-null   str
dtypes: float64(1), int64(1), str(7)
memory usage: 583.9 KB

In [4]:
euk_df.describe()

          Size (Mb)  Publication year
count   8302.000000       8302.000000
mean     401.918437       2015.849313
std     1111.538289          2.924305
min        0.011236       1992.000000
25%       19.249775       2015.000000
50%       39.559700       2017.000000
75%      258.848000       2018.000000
max    32396.400000       2019.000000

In [6]:
### You can sort by one or more columns
# euk_df.sort_values('Species', ascending=True).head()

### Sort by two columns; sort col1 first, then for rows with identical value in col1 are sorted according to col2
euk_df.sort_values(['Species', 'Publication year'], ascending=[True, False]).head()

,Species,Kingdom,Class,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status
2968,Abeoforma whisleri,Protists,Other Protists,101.5540,31.4,-,-,2017,Scaffold
3764,Abrus precatorius,Plants,Land Plants,347.2300,31.8,28735,40048,2018,Scaffold
2467,Absidia glauca,Fungi,Other Fungi,48.7464,44.5,15117,14891,2016,Scaffold
2695,Absidia repens,Fungi,Other Fungi,47.4229,38.2,15151,14915,2017,Contig
1905,Acanthamoeba astronyxis,Protists,Other Protists,83.4325,42.9,-,-,2015,Scaffold

### *Q1. How many fungal species have genomes size bigger than 100Mb? What are their names?*

**We need to filter a few things to address this question.**
1. Select all the Fungi under the "Kingdom" column.
2. Select all the Fungi with genome size greater than 100.
3. Select Species from the filtered data from step 2 above.

**Let's do it step by step. And then we will combine all of them in one line of code.**

In [9]:
### Filter dataframe and narrow down to only Kingdom that includes Fungi
euk_df[
    (euk_df["Kingdom"]=="Fungi")]

,Species,Kingdom,Class,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status
8,Saccharomyces cerevisiae S288C,Fungi,Ascomycetes,12.157100,38.1556,6445,6002,1999,Complete Genome
10,Pneumocystis carinii B80,Fungi,Ascomycetes,7.661460,27.8,3695,3646,2015,Contig
11,Schizosaccharomyces pombe,Fungi,Ascomycetes,12.591300,36.0381,6974,5132,2002,Chromosome
12,Aspergillus nidulans FGSC A4,Fungi,Ascomycetes,30.276000,50.2721,9586,9556,2003,Scaffold
13,Aspergillus fumigatus Af293,Fungi,Ascomycetes,29.385000,49.8105,19832,19260,2005,Chromosome
...,...,...,...,...,...,...,...,...,...
8297,Saccharomyces cerevisiae,Fungi,Ascomycetes,3.993920,38.2,-,-,2017,Scaffold
8298,Saccharomyces cerevisiae,Fungi,Ascomycetes,0.586761,38.5921,155,298,1992,Chromosome
8299,Saccharomyces cerevisiae,Fungi,Ascomycetes,12.020400,38.2971,-,-,2018,Chromosome
8300,Saccharomyces cerevisiae,Fungi,Ascomycetes,11.960900,38.2413,-,-,2018,Chromosome
8301,Saccharomyces cerevisiae,Fungi,Ascomycetes,11.820700,38.2536,-,-,2018,Chromosome

To **combine two conditional statements** in the filtering, we need to surround each conditional statements with its own pair of **parentheses**.

In [10]:
### Narrow down to Fungi that has genome size > 100
euk_df[
    (euk_df["Kingdom"]=="Fungi") &
    (euk_df["Size (Mb)"] > 100)
    ]

,Species,Kingdom,Class,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status
323,Blumeria graminis f. sp. hordei DH14,Fungi,Ascomycetes,124.489,43.5,-,-,2018,Scaffold
347,Puccinia triticina 1-1 BBBD Race 1,Fungi,Basidiomycetes,135.344,36.8,15539,15685,2009,Scaffold
354,Tuber melanosporum,Fungi,Ascomycetes,124.946,44.9,7496,7496,2010,Scaffold
372,Puccinia striiformis f. sp. tritici,Fungi,Basidiomycetes,156.834,44.4,-,-,2018,Contig
427,Melampsora larici-populina 98AG31,Fungi,Basidiomycetes,101.129,41.3,16380,16372,2011,Scaffold
...,...,...,...,...,...,...,...,...,...
6406,Rhizophagus irregularis,Fungi,Other Fungi,131.335,25.8,24574,24485,2016,Scaffold
6502,Rhizophagus irregularis,Fungi,Other Fungi,211.467,-,-,-,2018,Scaffold
6511,Rhizophagus irregularis,Fungi,Other Fungi,156.891,-,-,-,2018,Scaffold
6520,Puccinia striiformis,Fungi,Basidiomycetes,144.837,44.2,-,-,2019,Scaffold
6579,Puccinia striiformis f. sp. tritici CY32,Fungi,Basidiomycetes,130.485,45.2,-,-,2013,Scaffold

In [11]:
## To select Species that are Fungi with genome size > 100 Mb
euk_df[
    (euk_df["Kingdom"]=="Fungi") &
    (euk_df["Size (Mb)"] > 100)
    ].Species

323         Blumeria graminis f. sp. hordei DH14
347           Puccinia triticina 1-1 BBBD Race 1
354                           Tuber melanosporum
372          Puccinia striiformis f. sp. tritici
427            Melampsora larici-populina 98AG31
                          ...
6406                     Rhizophagus irregularis
6502                     Rhizophagus irregularis
6511                     Rhizophagus irregularis
6520                        Puccinia striiformis
6579    Puccinia striiformis f. sp. tritici CY32
Name: Species, Length: 76, dtype: str

Convert the Series from the above #Q1 to a python list using `to_list()` method

In [12]:
speciesList = euk_df[ (euk_df.Kingdom == 'Fungi') &
                  (euk_df['Size (Mb)'] > 100)
                 ]["Species"].to_list()

## Slice for the top 10 on the list
speciesList[0:10]

['Blumeria graminis f. sp. hordei DH14',
 'Puccinia triticina 1-1 BBBD Race 1',
 'Tuber melanosporum',
 'Puccinia striiformis f. sp. tritici',
 'Melampsora larici-populina 98AG31',
 'Ophiocordyceps sinensis',
 'Gigaspora rosea',
 'Leucoagaricus gongylophorus Ac12',
 'Hemileia vastatrix HvCat',
 'Cenococcum geophilum 1.58']

### Q2. How many organisms are there for each Kingdom (plants, animals, fungi, protists, and other), and how many unique species names?

*Hint*: Any time we see a question involving the words ”how many
... for each ...” the answer is `value_counts()`.

In [13]:
euk_df.Kingdom.value_counts()

Kingdom
Fungi       4494
Animals     2181
Plants       870
Protists     727
Other         30
Name: count, dtype: int64

To address "how many unique species names?", count the unique species names for plants by filtering the dataframe. [`nunique()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.nunique.html) returns the number of distinct, non-NA observations for each column (default) or row in a DataFrame

In [14]:
euk_df[(euk_df["Kingdom"] == "Plants")].Species.nunique()

464

In [15]:
### Write a loop to expand this to the other Kingdoms
Kingdoms = ["Protists", "Plants", "Animals"]

for k in Kingdoms:
    print(k, euk_df[euk_df.Kingdom == k].Species.nunique())

Protists 449
Plants 464
Animals 1442

#### To make the above more scalable
Hardcoding the values in kingdom is not scalable, we can implement a more elegant way to get a list of unique kingdom names directly from the dataframe [`unique()`](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.unique.html) returns unique values in the order of apperance. It does NOT sort.

In [20]:
### Return an array of unique values in Kingdom
unique_kingdoms = euk_df["Kingdom"].unique()

### Use an array to make it more scalable
for k in unique_kingdoms:
    print(k, euk_df[euk_df.Kingdom == k].Species.nunique())

Protists 449
Plants 464
Fungi 2554
Animals 1442
Other 27

### Q3. Make a new dataframe containing just the rows for the *Aquila* genus.

**Let go over some biology terminologies**
- The names under the **Species** column are scientific names that made up of a *genus* name and a *species* name separated by a space. Example: *Homo sapiens*. Note: there are some species that don't follow that format and we will ignore them for now.

To solve this problem, we will need to **separate the genus and species names** for each value in the **Species** column.

In [22]:
### Review how to split a string.
## What if we wanted to split string by ","?
a = "Homo sapiens"
a_split = a.split( )
print(a_split)
print(a_split[0])


# # Split the strings stored in the column Species
species_list = euk_df.Species.str.split(" ")
species_list

['Homo', 'sapiens']
Homo

0       [Emiliania, huxleyi, CCMP1516]
1              [Arabidopsis, thaliana]
2                       [Glycine, max]
3               [Medicago, truncatula]
4              [Solanum, lycopersicum]
                     ...
8297       [Saccharomyces, cerevisiae]
8298       [Saccharomyces, cerevisiae]
8299       [Saccharomyces, cerevisiae]
8300       [Saccharomyces, cerevisiae]
8301       [Saccharomyces, cerevisiae]
Name: Species, Length: 8302, dtype: object

In [23]:
## Take the first element of each of the resulting lists (again remembering to refer to the str attribute):
## This gives us our series of genus names.
euk_df.Species.str.split().str[0]

0           Emiliania
1         Arabidopsis
2             Glycine
3            Medicago
4             Solanum
            ...
8297    Saccharomyces
8298    Saccharomyces
8299    Saccharomyces
8300    Saccharomyces
8301    Saccharomyces
Name: Species, Length: 8302, dtype: object

In [24]:
## Add the condition to get a series of boolean values:
euk_df.Species.str.split(' ').str[0] == "Aquila"

0       False
1       False
2       False
3       False
4       False
        ...
8297    False
8298    False
8299    False
8300    False
8301    False
Name: Species, Length: 8302, dtype: bool

In [28]:
## Plug the above into the original dataframe to select the rows that are True
aquila_data = euk_df[ (euk_df.Species.str.split(' ').str[0] == "Aquila") ]
aquila_data.head()

,Species,Kingdom,Class,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status,Genus
1755,Aquila chrysaetos canadensis,Animals,Birds,1192.74,41.9001,17520,31284,2014,Scaffold,Aquila
4388,Aquila chrysaetos canadensis,Animals,Birds,1548.48,43.5,-,-,2014,Scaffold,Aquila
5342,Aquila chrysaetos chrysaetos,Animals,Birds,1228.51,42.2,-,-,2018,Scaffold,Aquila

In [29]:
## Extract the genus name and combine it with other columns in the dataframe to create a new dataframe
euk_df['Genus']=euk_df.Species.str.split(" ").str[0]

neweuk = euk_df[["Species","Genus","Class","Kingdom"]]
neweuk.head()

                      Species        Genus           Class   Kingdom
0  Emiliania huxleyi CCMP1516    Emiliania  Other Protists  Protists
1        Arabidopsis thaliana  Arabidopsis     Land Plants    Plants
2                 Glycine max      Glycine     Land Plants    Plants
3         Medicago truncatula     Medicago     Land Plants    Plants
4        Solanum lycopersicum      Solanum     Land Plants    Plants

### Q4. Which organism have at least 10% more proteins than genes?

There are a few different ways to interpret ”10% more”, but for the purposes of this question we will say that we want to divide the number of proteins by the number of genes, and if the result is greater than or equal to 1.1 then we want to include the organism.

If you look at the `euk` dataframe, you will see that the columns **Number of proteins** and **Number of genes** are mixed with numeric values and dashes. To ensure that all the values in these two columns are numeric, we will use pandas method [`to_numeric`](https://pandas.pydata.org/pandas-docs/version/0.19.2/generated/pandas.to_numeric.html) to covert the values to numeric. We will set the `errors` argument to `'coerce'` to convert any non-numeric value to NaN (not a number).

In [ ]:
### Calculate proteins per gene by applying the division for each row. What to do about NaN?
# euk_df["Proteins per gene"] = euk_df["Number of proteins"]/euk_df["Number of genes"]
# euk_df["Proteins per gene"]

In [30]:
### What happens if there are non-numeric value in a column?
# euk_df["Number of proteins"] =  pd.to_numeric(euk_df["Number of proteins"])
# euk_df["Number of proteins"].mean()

euk_df["Number of proteins"] =  pd.to_numeric(euk_df["Number of proteins"], errors='coerce' )
euk_df["Number of genes"] =  pd.to_numeric(euk_df["Number of genes"], errors='coerce' )
euk_df["GC%"] =  pd.to_numeric(euk_df["GC%"],  errors='coerce')

euk_df["Proteins per gene"] = euk_df["Number of proteins"]/euk_df["Number of genes"]
euk_df.head()

,Species,Kingdom,Class,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status,Genus,Proteins per gene
0,Emiliania huxleyi CCMP1516,Protists,Other Protists,167.676,64.5000,38549.0,38554.0,2013,Scaffold,Emiliania,1.000130
1,Arabidopsis thaliana,Plants,Land Plants,119.669,36.0529,38311.0,48265.0,2001,Chromosome,Arabidopsis,1.259821
2,Glycine max,Plants,Land Plants,979.046,35.1153,59847.0,71219.0,2010,Chromosome,Glycine,1.190018
3,Medicago truncatula,Plants,Land Plants,412.924,34.0470,37603.0,41939.0,2011,Chromosome,Medicago,1.115310
4,Solanum lycopersicum,Plants,Land Plants,828.349,35.6991,31200.0,37660.0,2010,Chromosome,Solanum,1.207051

In [31]:
### To filter the rows where the ratio of proteins and genes is
## greater than or equal to 1.1, we will get a series of boolean
## values by setting the condition.

euk_df[(euk_df["Proteins per gene"] >= 1.1)]

,Species,Kingdom,Class,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status,Genus,Proteins per gene
1,Arabidopsis thaliana,Plants,Land Plants,119.669000,36.0529,38311.0,48265.0,2001,Chromosome,Arabidopsis,1.259821
2,Glycine max,Plants,Land Plants,979.046000,35.1153,59847.0,71219.0,2010,Chromosome,Glycine,1.190018
3,Medicago truncatula,Plants,Land Plants,412.924000,34.0470,37603.0,41939.0,2011,Chromosome,Medicago,1.115310
4,Solanum lycopersicum,Plants,Land Plants,828.349000,35.6991,31200.0,37660.0,2010,Chromosome,Solanum,1.207051
6,Oryza sativa Japonica Group,Plants,Land Plants,374.423000,43.5769,35219.0,42580.0,2015,Chromosome,Oryza,1.209007
...,...,...,...,...,...,...,...,...,...,...,...
6487,Fusarium oxysporum f. sp. melonis 26406,Fungi,Ascomycetes,54.034300,47.5000,20030.0,26719.0,2012,Scaffold,Fusarium,1.333949
6523,Fusarium oxysporum Fo47,Fungi,Ascomycetes,49.664600,47.7000,18553.0,24818.0,2012,Scaffold,Fusarium,1.337681
6626,Arabidopsis thaliana,Plants,Land Plants,93.654500,36.0433,16842.0,20111.0,2000,Chromosome,Arabidopsis,1.194098
6781,Mus musculus,Animals,Mammals,3251.250000,41.8306,31682.0,45437.0,2005,Chromosome,Mus,1.434158
8298,Saccharomyces cerevisiae,Fungi,Ascomycetes,0.586761,38.5921,155.0,298.0,1992,Chromosome,Saccharomyces,1.922581

### Indexing in pandas
The indexing operator and attribute selection are nice because they work just like they do in the rest of the Python ecosystem. As a novice, this makes them easy to pick up and use. However, pandas has its own accessor operators, `iloc` and `loc`. For more advanced operations, these are the ones you're supposed to be using.

#### Index-based selection
Pandas indexing works in one of two paradigms. The first is index-based selection: selecting data based on its numerical position in the data.`iloc` follows this paradigm.

To select the first row of data in a DataFrame, we may use the following:

In [32]:
### New df of only Fungi Kingdom
fungi = euk_df[(euk_df.Kingdom == 'Fungi')]

## Selecting first row
fungi.iloc[0]

Species               Saccharomyces cerevisiae S288C
Kingdom                                        Fungi
Class                                    Ascomycetes
Size (Mb)                                    12.1571
GC%                                          38.1556
Number of genes                               6445.0
Number of proteins                            6002.0
Publication year                                1999
Assembly status                      Complete Genome
Genus                                  Saccharomyces
Proteins per gene                           0.931265
Name: 8, dtype: object

## Extracting rows and columns

-  Extract specific rows and all columns

    ```df.iloc[rows]```

-  Extract specific rows and columns

    ```df.iloc[rows, columns]```

-  Extract specific rows and columns with specific indices

    ```df.iloc[start:stop:skip, start:stop:skip]```

#### Note that stop is exclusive

 ```[1:3]``` will extract the second and third rows for all columns.

```[1::2, :]```  will extract from the 2nd row all the way to the end every other row, and all the columns

```[:, :3]```  all rows, from the beginning to the 3rd column (indices 0, 1, 2)

In [33]:
# ## Getting the second and third rows for all columns
fungi.iloc[1:3]

,Species,Kingdom,Class,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status,Genus,Proteins per gene
10,Pneumocystis carinii B80,Fungi,Ascomycetes,7.66146,27.8000,3695.0,3646.0,2015,Contig,Pneumocystis,0.986739
11,Schizosaccharomyces pombe,Fungi,Ascomycetes,12.59130,36.0381,6974.0,5132.0,2002,Chromosome,Schizosaccharomyces,0.735876

In [34]:
# Getting every other rows from the first row to the 10th row, and extracting 4th and 5th columns
fungi.iloc[0:10:2, 3:5]

    Size (Mb)      GC%
8    12.15710  38.1556
11   12.59130  36.0381
13   29.38500  49.8105
15   14.28270  33.4827
33    2.49752  47.3005

Both loc and iloc are row-first, column-second. This is the opposite of what we do in native Python, which is column-first, row-second.

This means that it's marginally easier to retrieve rows, and marginally harder to get retrieve columns. To get a column with iloc, we can do the following:

In [35]:
## Select all rows, first column
fungi.iloc[:, 0]

8       Saccharomyces cerevisiae S288C
10            Pneumocystis carinii B80
11           Schizosaccharomyces pombe
12        Aspergillus nidulans FGSC A4
13         Aspergillus fumigatus Af293
                     ...
8297          Saccharomyces cerevisiae
8298          Saccharomyces cerevisiae
8299          Saccharomyces cerevisiae
8300          Saccharomyces cerevisiae
8301          Saccharomyces cerevisiae
Name: Species, Length: 4494, dtype: str

On its own, the `:` operator, which also comes from native Python, means "everything". When combined with other selectors, however, it can be used to indicate a range of values. For example, to omit the first 3 columns and extract just the first three rows, we would do:

In [36]:
fungi.iloc[:3, 3:]

,Size (Mb),GC%,Number of genes,Number of proteins,Publication year,Assembly status,Genus,Proteins per gene
8,12.15710,38.1556,6445.0,6002.0,1999,Complete Genome,Saccharomyces,0.931265
10,7.66146,27.8000,3695.0,3646.0,2015,Contig,Pneumocystis,0.986739
11,12.59130,36.0381,6974.0,5132.0,2002,Chromosome,Schizosaccharomyces,0.735876

#### Label-based selection
The second paradigm for attribute selection is the one followed by the loc operator: label-based selection. In this paradigm, it's the data index value, not its position, which matters.

In [37]:
## Getting all rows, and specific columns based on their headers
fungi.loc[:, ['Species', 'Number of genes', 'Number of proteins']]

                             Species  Number of genes  Number of proteins
8     Saccharomyces cerevisiae S288C           6445.0              6002.0
10          Pneumocystis carinii B80           3695.0              3646.0
11         Schizosaccharomyces pombe           6974.0              5132.0
12      Aspergillus nidulans FGSC A4           9586.0              9556.0
13       Aspergillus fumigatus Af293          19832.0             19260.0
...                              ...              ...                 ...
8297        Saccharomyces cerevisiae              NaN                 NaN
8298        Saccharomyces cerevisiae            155.0               298.0
8299        Saccharomyces cerevisiae              NaN                 NaN
8300        Saccharomyces cerevisiae              NaN                 NaN
8301        Saccharomyces cerevisiae              NaN                 NaN

[4494 rows x 3 columns]

### Set row index using a specific column

In [ ]:
### Set index as Species for fungi df

### Reset dataframe's index

In [ ]:
### Can you retrieve the condition of GC% > 50.00?
GC_fungi = fungi[fungi['GC%'] > 50.00]

In [ ]:
### Need to reset the index because GC_fungi is multitier

In [ ]:
# Getting specific rows based on the row index and all columns
fungi.loc[['Saccharomyces cerevisiae'], :]

In [ ]:
fungi.reset_index(inplace=True)
fungi.head()

**Data visualizing with Pie plot**  
Dataframe has a built-in pie chart plotting(https://pandas.pydata.org/docs/reference/api/pandas.DataFrame.plot.pie.html). While it is not as customizable as later libraries that we will use such as matplotlib, it allows us to quickly plot a pie chart from the dataframe. Additionally you can specify the size plot you want to return using the parameter figsize).

In [ ]:
## Pass in the column that you want to plot as your "y" variable.
fungi.plot.pie(y='Publication year', figsize=(5, 5))